#!/bin/bash

#to show message during first startup
/usr/bin/echo "*******************************************************************************"
/usr/bin/echo "  Amahi Server is Being Setup. Please Be Patient. It may take"
/usr/bin/echo "  several minutes. It will automatically reboot..................."
/usr/bin/echo "********************************************************************************"

